### ISSUE TITLE
Update to current?

### ISSUE THREAD

**Issue by jenstroeger** [jbernard/pwgen#1]
It looks like [pwgen on Sourceforge](https://sourceforge.net/projects/pwgen/) continued to develop, with the latest update on 2016-11-29. It seems that therefore this Github repo is stale, and development happens over at Sourceforge?

**Comment by jbernard** [comment]
* Jens Troeger <notifications@github.com> wrote:
> It looks like [pwgen on
> Sourceforge](https://sourceforge.net/projects/pwgen/) continued to
> develop, with the latest update on 2016-11-29. It seems that therefore
> this Github repo is stale, and development happens over at
> Sourceforge?

Yes, the sourceforge site wasn't always available and this repo served
as a mirror during that time.  Ted is both the original author and the
admin for the sourceforge site, so I would consider it to be the
primary repository for the project.

-- 
Jon

**Comment by jenstroeger** [comment]
Thanks @jbernard. I’ve contacted him to ask about preferences, and if he’d possibly consider moving to Github...
